branch-protection:
  enforce_admins: true # rules apply to admins
  restrictions:
    teams: ["maintainers", "machine_users"]
  required_pull_request_reviews:
    dismiss_stale_reviews: true # automat dismiss old reviews
    dismissal_restrictions: # allow review dismissals
      teams:
      - maintainers
      - machine_users
    required_approving_review_count: 1 # number of approvals
  required_status_checks:
    strict: false # we don't want to block any PR if it's not up to date, we have the rebase merge strategy and needs-rebase plugin
  orgs:
    falcosecurity:
      required_status_checks:
        contexts:
        - dco
      repos:
        client-go:
          branches:
            master:
              protect: true
        client-py:
          branches:
            master:
              protect: true
        falco:
          required_status_checks:
            contexts:
            - Travis CI - Pull Request
          branches:
            agent-master:
              protect: true
            dev:
              protect: true
            master:
              protect: true
        falco-exporter:
          branches:
            master:
              protect: true
        falcoctl:
          branches:
            master:
              protect: true
        falco-website:
          branches:
            master:
              protect: true
        community:
          branches:
            master:
              protect: true
        test-infra:
          branches:
            master:
              protect: true

log_level: debug

# todo > use placeholders in comment? https://github.com/kubernetes/test-infra/blob/888ff5ffe5991efad27997c7bd176e37a9a85b2f/robots/commenter/main.go#L44
periodics:
  - name: periodic-stale
    interval: 1h
    decorate: false
    spec:
      containers:
      - image: gcr.io/k8s-prow/commenter:v20190528-0d7c4b53a
        command:
        - /app/robots/commenter/app.binary
        args:
        - |-
          --query=org:falcosecurity
          -label:lifecycle/frozen
          -label:lifecycle/stale
          -label:lifecycle/rotten
        - --updated=2160h
        - --token=/etc/github/oauth
        - |-
          --comment=Issues go stale after 90d of inactivity.
          Mark the issue as fresh with `/remove-lifecycle stale`.
          Stale issues rot after an additional 30d of inactivity and eventually close.
          If this issue is safe to close now please do so with `/close`.
          Provide feedback via https://github.com/falcosecurity/community.
          /lifecycle stale
        - --template
        - --confirm
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token

  - name: periodic-close
    interval: 1h
    decorate: false
    spec:
      containers:
      - image: gcr.io/k8s-prow/commenter:v20190528-0d7c4b53a
        command:
        - /app/robots/commenter/app.binary
        args:
        - |-
          --query=org:falcosecurity
          -label:lifecycle/frozen
          label:lifecycle/rotten
        - --updated=720h
        - --token=/etc/github/oauth
        - |-
          --comment=Rotten issues close after 30d of inactivity.
          Reopen the issue with `/reopen`.
          Mark the issue as fresh with `/remove-lifecycle rotten`.
          Provide feedback via https://github.com/falcosecurity/community.
          /close
        - --template
        - --confirm
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: oauth
        secret:
        secretName: oauth-token

  - name: periodic-rotten
    interval: 1h
    decorate: false
    spec:
      containers:
      - image: gcr.io/k8s-prow/commenter:v20190528-0d7c4b53a
        command:
        - /app/robots/commenter/app.binary
        args:
        - |-
          --query=org:falcosecurity
          -label:lifecycle/frozen
          label:lifecycle/stale
          -label:lifecycle/rotten
        - --updated=720h
        - --token=/etc/github/oauth
        - |-
          --comment=Stale issues rot after 30d of inactivity.
          Mark the issue as fresh with `/remove-lifecycle rotten`.
          Rotten issues close after an additional 30d of inactivity.
          If this issue is safe to close now please do so with `/close`.
          Provide feedback via https://github.com/falcosecurity/community.
          /lifecycle rotten
        - --template
        - --confirm
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        volumes:
        - name: oauth
          secret:
          secretName: oauth-token


pod_namespace: test-pods

prowjob_namespace: default

tide:
  context_options:
    skip-unknown-contexts: true
    from-branch-protection: true
  merge_method:
    falcosecurity/client-go: rebase
    falcosecurity/client-py: rebase
    falcosecurity/falco: rebase
    falcosecurity/falco-exporter: rebase
    falcosecurity/falcoctl: rebase
    falcosecurity/falco-website: rebase
    falcosecurity/community: rebase
    falcosecurity/test-infra: rebase
  queries:
  - repos:
    - falcosecurity/client-go
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/falco
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/client-py
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/falco
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/falco-exporter
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/falco
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/falcoctl
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/falco-website
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
  - repos:
    - falcosecurity/community
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
  - repos:
    - falcosecurity/test-infra
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
