branch-protection:
  orgs:
    falcosecurity:
      repos:
        office-hours:
          branches:
            master:
              protect: true
          enforce_admins: true # rules apply to admins
          restrictions:
            teams: ["admins", "machine_users"] # always allow team "admins" to push
          required_pull_request_reviews:
            dismiss_stale_reviews: true # automatically dismiss old reviews
            dismissal_restrictions: # allow review dismissals
              teams:
              - admins
            required_approving_review_count: 1 # number of approvals
          required_status_checks:
            strict: true # require PR branch to be up to date
        test-infra:
          branches:
            master:
              protect: true
          enforce_admins: true
          restrictions:
            teams: ["admins", "machine_users"]
          required_pull_request_reviews:
            dismiss_stale_reviews: true # automatically dismiss old reviews
            dismissal_restrictions: # allow review dismissals
              teams:
              - admins
            required_approving_review_count: 1 # number of approvals
          required_status_checks:
            strict: true # require PR branch to be up to date

log_level: debug

plank:
  job_url_prefix: https://prow.gflocks.com/view/gcs/
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 2h
    grace_period: 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190506-d97b87848"
      initupload: "gcr.io/k8s-prow/initupload:v20190506-d97b87848"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190506-d97b87848"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190506-d97b87848"
    # fixme > complete GCS (or alternative?) configuration
    # gcs_configuration:
    #   bucket: "..."
    #   path_strategy: "explicit"
    # gcs_credentials_secret: "service-account"

pod_namespace: test-pods

prowjob_namespace: default

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 24h

tide:
  merge_method:
    falcosecurity/office-hours: rebase
    falcosecurity/test-infra: rebase
  queries:
  - repos:
    - falcosecurity/falco
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progess
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/office-hours
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progess
    - needs-rebase
  - repos:
    - falcosecurity/test-infra
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progess
    - needs-rebase
