branch-protection:
  enforce_admins: true # rules apply to admins
  restrictions:
    teams: ["maintainers", "machine_users"]
  required_pull_request_reviews:
    dismiss_stale_reviews: true # automat dismiss old reviews
    dismissal_restrictions: # allow review dismissals
      teams:
      - maintainers
      - machine_users
    required_approving_review_count: 1 # number of approvals
  required_status_checks:
    strict: true # require PR branch to be up to date
  orgs:
    falcosecurity:
      required_status_checks:
        contexts:
          - dco
      repos:
        falco:
          required_status_checks:
            contexts:
              - "Travis CI - Branch"
              - "Travis CI - Pull Request"
          branches:
            agent-master:
              protect: true
            dev:
              protect: true
            master:
              protect: true
        office-hours:
          branches:
            master:
              protect: true
        test-infra:
          branches:
            master:
              protect: true

log_level: debug

pod_namespace: test-pods

presubmits:
  falcosecurity/test-infra:
  - name: check-prow-config
    branches:
    - master
    decorate: false # todo(fntlnz,leodido): we need plank for this, but it has a bug that only make it work on gcs
    always_run: true
    skip_report: false
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20190607-6c71cb47c
          imagePullPolicy: Always
          command:
          - /checkconfig
          args:
          - --config-path=/etc/config/configs.yaml

prowjob_namespace: default

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 24h

tide:
  context_options:
    skip-unknown-contexts: true
    from-branch-protection: true
  merge_method:
    falcosecurity/falco: rebase
    falcosecurity/office-hours: rebase
    falcosecurity/test-infra: rebase
  queries:
  - repos:
    - falcosecurity/falco
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - do-not-merge/release-note-label-needed
    - needs-rebase
  - repos:
    - falcosecurity/office-hours
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
  - repos:
    - falcosecurity/test-infra
    labels:
    - approved
    - lgtm
    - "dco-signoff: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
