config_updater:
  config_file: prow/config/config.yaml
  plugins_file: prow/config/plugins.yaml
  maps:
    prow/config/config.yaml:
      name: config
    prow/config/plugins.yaml:
      name: plugins

require_matching_label:
  - missing_label: needs-kind
    org: falcosecurity
    repo: office-hours
    issues: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this proposal.
      Whether it refers to an issue or to a PR in [Falco](https://github.com/falcosecurity/falco).
      Please specify it either using `/kind <group>` or manually from the side menu.
      In case you do not know which kind this proposal is please mention the maintainers using `@team/maintainers`.

label:
  additional_labels:
    - kind/pr
    - kind/issue

plugins:
  falcosecurity/test-infra:
    - config-updater
  falcosecurity/office-hours:
    - blunderbuss
    - label
    - lgtm
    - require-matching-label
