presubmits:
  falcosecurity-test/test-infra:
    - name: check-prow-config
      branches:
        - ^master$
      decorate: true
      skip_report: false
      run_if_changed: '^(config/local/(config|plugins).yaml$|config/local/jobs/.*.yaml$)'
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20220318-1a1db3d5d8
            command:
              - checkconfig
            args:
              - --config-path=config/local/config.yaml
              - --job-config-path=config/local/jobs
              - --plugin-config=config/local/plugins.yaml
              - --strict
        nodeSelector:
          Archtype: "x86"

periodics:
- name: check-prow-config-periodic
  interval: 1h
  decorate: true
  extra_refs:
    - org: falcosecurity-test
      repo: test-infra
      base_ref: master
  spec:
    containers:
      - image: gcr.io/k8s-prow/checkconfig:v20220318-1a1db3d5d8
        command:
          - checkconfig
        args:
          - --config-path=config/local/config.yaml
          - --job-config-path=config/local/jobs
          - --plugin-config=config/local/plugins.yaml
          - --strict
    nodeSelector:
      Archtype: "x86"
